ignore-paths:
    - doc
    - cli.py
    - test
    - alembic
    - app_context_rqworker.py
    - warm.py
    - run.py
    - settings_local.py
    - ./update.py
pylint:
    disable:
        - E0611
        - F0401
        - W0613
        - R0401
        - W0614
        - W1401
    options:
        dummy-variables-rgx: _|dummy
