language: python
python:
  - "2.6"
  - "2.7"
env: 
  - PYBOSSA_SETTINGS='../settings_test.py' PYBOSSA_REDIS_CACHE_DISABLED='1'
services:
  - redis-server
before_install:
  - sudo apt-get update && sudo apt-get install swig
  - redis-server --version
  - redis-server contrib/sentinel.conf --sentinel
install:
  - python setup.py install
  - pip install -r cache_requirements.txt
before_script:
  - psql -c 'create database pybossa;' -U postgres
script: nosetests
notifications:
  email: false
  irc: "irc.freenode.net#okfn-dev"
